brapi_shared_study_names
PhenoApps/Field-Book pull request #1095
Opened 2024-12-04 21:07 UTC by chaneylc

### Change Type

- [ ] **`ADDITION`** (non-breaking change that adds functionality)
- [x] **`CHANGE`** (fix or feature that alters existing functionality)
- [ ] **`FIX`** (non-breaking change that resolves an issue)
- [ ] **`OTHER`** (use only for changes like tooling, build system, CI, docs, etc.)

### Release Note

```release-note

```
___

### Release Type

_For internal use - please leave these unchecked unless you are the one completing the merge._

- [ ] **`MAJOR`**
- [ ] **`MINOR`**
- [ ] **`WAIT`** (No immediate release, but the changelog will be still be updated if there is a release note.)

2024-12-04 21:51 UTC, trife requested changes
I don't think we should include the study dbid in the listitem.

2024-12-05 22:19 UTC, chaneylc commented
I can remove it, but then we need a way to differentiate between studies with the same name.

2024-12-07 12:50 UTC, trife commented
Duplicate or non-descriptive names is against the recommended pattern for Field Book but isn't against the brapi spec. We can eventually group brapi studies by trial to side step this, but it's not a priority for now.

2024-12-11 09:04 UTC, trife approved these changes

2024-12-11 09:04 UTC, merged