validate_categorical_barcode_data
PhenoApps/Field-Book pull request #1110
Opened 2024-12-10 20:38 UTC by chaneylc

### Change Type

- [ ] **`ADDITION`** (non-breaking change that adds functionality)
- [ ] **`CHANGE`** (fix or feature that alters existing functionality)
- [x] **`FIX`** (non-breaking change that resolves an issue)
- [ ] **`OTHER`** (use only for changes like tooling, build system, CI, docs, etc.)

### Release Note

```release-note

```
___

### Release Type

_For internal use - please leave these unchecked unless you are the one completing the merge._

- [ ] **`MAJOR`**
- [ ] **`MINOR`**
- [ ] **`WAIT`** (No immediate release, but the changelog will be still be updated if there is a release note.)

2024-12-11 09:15 UTC, trife requested changes
Add validation for percent traits

2025-01-04 01:46 UTC, trife approved these changes

2025-01-04 01:46 UTC, merged

2025-03-10 15:51 UTC, pthyde123 commented
We are using and Alacrity 433 Bluetooth Wireless Barcode Scanner with a Samsung Galaxy Tab  A7 Lite to run FieldBook version 6.0.8.  If I download the numeric trait Plant height - cm|CO_350:0000232 from T3-Oat and try collecting data I cannot switch from the numeric keypad displayed to the barcode scanner which is connected via Bluetooth to the tablet as an external keyboard.  Is there a way to make this connection or do traits collected with a barcode scanner currently need to be in text format?  Thanks

2025-03-11 08:04 UTC, trife commented
@pthyde123 discussion for this is in #1173