Database refactor
PhenoApps/Field-Book pull request #183
Opened 2020-11-05 22:06 UTC by chaneylc

# Description

The motivation of this pull request is to modularize and refactor the back-end for a new schema update. Every table in the new schema has a respective model, along with new queries and functions that replace the DataHelper functions. 

The new schema mapping: 
[field_book_database_mapping_20200902.xlsx](https://github.com/PhenoApps/Field-Book/files/5497462/field_book_database_mapping_20200902.xlsx)

The new back-end files are in com.fieldbook.tracker.database. Model files are included for each table in the new schema. Most queries belong to a given module, otherwise they're included in the DataHelper2.kt utility file. For example, 'updateExpTable()' in DataHelper is equivalent to 'StudyModel.updateExpTable()' in the StudyModel file because the old schema table exp_id is now the studies table which has a StudyModel Kotlin file implementation. But currently the ObservationUnitProperty (new range table) table has no individual model file, so it has functions in the DataHelper2.kt file.

I commented out a line in DataHelper.java line 1686, this makes the function more test-friendly, but this might cause issues in ConfigActivity if the database wasn't opened before this call.

Furthermore, this pull request contains two new files for testing the back-end schema change. One file, DatabaseBatchTest is for testing a set of databases. DatabaseTest is for testing individual databases. The tests expect an old database to be present, which is loaded at the beginning of each test, before the test is run the new schema tables are created. 

There is a test for every function in DataHelper, each test runs the old back-end and notifies if it fails. If the old back-end does not fail, the new back-end is run and the queries are compared. Query comparison is dependent on the function, order is matched when necessary. Generally, if a function returns a cursor then the column names and values are matched; otherwise, if an object s.a a FieldObject is returned, then each member within the object is checked. There are some exceptions, including last_synced_time with observations.

Some issues with the DataHelper.java back-end have been found with these tests. Specifically, some databases seem to have row data that has BLOB, and NUMERIC affinity. This causes some data to be missed in the export functions, s.a url's, and some integer values. These tests can be used to reproduce SQLite errors in regards to the 64 limit join queries. Another issue found in DataHelper was the sanitization of queries. Two distinct problems occurred when blank columns or identifiers were used, specifically when plot attribute names were blank values. Secondly, when identifiers were quoted with ' and contained '.  https://sqlite.org/lang_keywords.html brackets or grave accents are recommended for this.

Kotlin is now a dependency.

## Type of change

- [X ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
I marked this as a breaking change because of the line 1686 comment in DataHelper. We might need a better way to ensure the database is open before queries are run in CollectActivity.

# How Has This Been Tested?

The app runs on emulator, but runs into database access issues in CollectActivity.

2020-11-25 20:23 UTC, timparsons commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
> +                             notes: String, exp_id: String, observationDbId: String?,
Is there any intention of storying `notes` and `observationDbId`?  If not, I'd recommend removing them

2020-11-25 23:21 UTC, timparsons requested changes
Overall, looks like a really nice improvement to the structure of the code.  I do have some comments and suggestions:

- Each of the schema models has a PK and FK constant.  Why aren't the rest of the columns in the table represented as constants?

- There are a number of queries that are doing comparisons using `LIKE`, when it appears they should be using `=`.  For example, the where clause in `ObservationDAO->getObservation` (line 113).

- Other than a handful of methods, the DataHelper doesn't look like it does much other than wrap around the DAOs.  Are there plans to refactor current calls to the DataHelper, and instead call directly to the DAOs?

- Look into database versioning
	This is a large effort in and of itself, so I wouldn't suggest doing it within this effort.
	
	There are libraries that exist that can version a database, and upgrade it when needed.  Your code base would have migration scripts that start at the very beginning of the initial creation of the database, and then have additional scripts added over time for changes made (updates, creation of new tables, modification of existing data, etc), and the library handles applying these scripts to the database automatically.  Flyway (flywaydb.org) is a nice library that only requires you to make sql files with a specific name format in order for it to know the order in which to apply the patches.

- Look into dependency injection
	This is a large effort in and of itself, so I wouldn't suggest doing it within this effort.

	https://developer.android.com/training/dependency-injection

	@BrapiCoordinatorSelby and I both have extensive experience using Google Guice, and have enough knowledge of Dagger to help with any questions.  Here's a guide for using Dagger in Android: https://developer.android.com/training/dependency-injection/dagger-android

	I'm noticing how the DataHelper is created for each Activity within the `onCreate` method.  I would suggest that `DataHelper` become a singleton, and is therefore only created once.  If using dependency injection, this is very easy to define the `DataHelper` as a singleton.  Activity classes would also become more modular and more testable because they wouldn't create new instances of `DataHelper` (or any other dependencies) on their own, but rather, have it injected.

2020-12-03 17:15 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +                    e.printStackTrace()
From my understanding of the docs, a rollback automatically occurs if setTransactionSuccessful is not called. 
https://developer.android.com/reference/androidx/sqlite/db/SupportSQLiteDatabase
db.beginTransaction();
   try {
     ...
     db.setTransactionSuccessful();
   } finally {
     db.endTransaction();
   }

2020-12-03 17:18 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +            deleteTables()
Nice catch, I moved this into the transaction.

2020-12-03 17:19 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/SqlUtil.kt
> +
This function is no longer used.

2020-12-03 17:22 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/SqlUtil.kt
> +        ie.printStackTrace()
I moved these catches to the withDatabase function. The toFirst and toTable functions are called with withDatabase on the callstack, so these exceptions are now propagated to the withDatabase exception handler.

2020-12-03 17:24 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/SqlUtil.kt
> +    }
Again, I moved these to the withDatabase function.

2020-12-03 17:27 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/SqlUtil.kt
> +}
These are not propagated because there is no guarantee that the calling method is catching errors. If a backend error (SQLiteException) occurs, then the app would crash. The original idea was to return null if any error occurred. I suppose when we implement ViewModels, these errors could be handled there instead, which might be a bit cleaner.

2020-12-03 17:33 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +                    }
I cleaned this up and moved the catches to the calling method.

2020-12-03 17:47 UTC, timparsons commented on app/src/main/java/com/fieldbook/tracker/database/SqlUtil.kt
> +}
>I suppose when we implement ViewModels, these errors could be handled there instead, which might be a bit cleaner.

I think that would be the right direction to go.  I would think you would want the view responsible for making the call to the database to know about any errors so you can inform the end-user.

2020-12-03 17:53 UTC, chaneylc commented
Thanks for putting time into reviewing this pull request. You mention a lot of useful libraries and helpful fixes :)

>     * Each of the schema models has a PK and FK constant.  Why aren't the rest of the columns in the table represented as constants?
That part was a little rushed, you're correct they should be added as constants.
 
>     * There are a number of queries that are doing comparisons using `LIKE`, when it appears they should be using `=`.  For example, the where clause in `ObservationDAO->getObservation` (line 113).
These operators are used in the original backend queries, I didn't want to break any functionality. This is also something I'm curious about because if no patterns are used in these operations then we should switch to the equality operator.

>     * Other than a handful of methods, the DataHelper doesn't look like it does much other than wrap around the DAOs.  Are there plans to refactor current calls to the DataHelper, and instead call directly to the DAOs?
Not currently, but eventually we can implement ViewModels that will call the dao queries.

>     * Look into database versioning
>       This is a large effort in and of itself, so I wouldn't suggest doing it within this effort.
>       There are libraries that exist that can version a database, and upgrade it when needed.  Your code base would have migration scripts that start at the very beginning of the initial creation of the database, and then have additional scripts added over time for changes made (updates, creation of new tables, modification of existing data, etc), and the library handles applying these scripts to the database automatically.  Flyway (flywaydb.org) is a nice library that only requires you to make sql files with a specific name format in order for it to know the order in which to apply the patches.
Interesting, I will keep this in mind. Thanks!

>     * Look into dependency injection
>       This is a large effort in and of itself, so I wouldn't suggest doing it within this effort.
>       https://developer.android.com/training/dependency-injection
>       @BrapiCoordinatorSelby and I both have extensive experience using Google Guice, and have enough knowledge of Dagger to help with any questions.  Here's a guide for using Dagger in Android: https://developer.android.com/training/dependency-injection/dagger-android
>       I'm noticing how the DataHelper is created for each Activity within the `onCreate` method.  I would suggest that `DataHelper` become a singleton, and is therefore only created once.  If using dependency injection, this is very easy to define the `DataHelper` as a singleton.  Activity classes would also become more modular and more testable because they wouldn't create new instances of `DataHelper` (or any other dependencies) on their own, but rather, have it injected.
This is a great discussion topic for the overall architecture of FieldBook. I think eventually we can modularly implement a more jetpack-like architecture, and here Dagger Android / Hilt / ButterKnife will fit perfectly. After completing this back-end refactoring, we can focus on implementing DI for ViewModels (and other Android classes).

2020-12-04 22:01 UTC, BrapiCoordinatorSelby commented
@chaneylc 
quick note: do a `gradle :app:clean` then a `gradle :app:compileDebugKotlin` and you'll get a list of Kotlin warnings. Take a quick look through them to catch unused variables etc. I see about 14. Not a big deal, but will help clean up a little.
Stupid gradle seems to ignore them unless you explicitly clean first 🤦

2020-12-04 22:15 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
>                      case 2:
Suggestion: use the same code for both `case 2` and `case 3`, perhaps move this code to a method

2020-12-04 23:44 UTC, BrapiCoordinatorSelby commented
FYI I opened #195 so one of us will remember to go look at the timestamp inconsistencies.

2020-12-04 23:49 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
> +        fun updateImage(image: Image, writeLastSyncedTime: Boolean) {
Is there a reason why this method follows a different `withDatabase` pattern? It looks equivalent, just curious why the difference

2020-12-07 22:01 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
> +        Observation o = ObservationDao.Companion.getObservation(plotId, parent);
Make this a `return` statement like others

2020-12-07 22:30 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
> +        if (!isTableExists("ObservationUnitProperty")) {
Is this ever expected to happen? Is there a use case where it is important to get the `observationUnitProperties` for the first field? even though that field has not been selected yet and there might not even be a first field to get? Maybe this should be part of a unit test setup rather than built into the method?

2020-12-07 23:08 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
>          if (db == null || !db.isOpen()) db = openHelper.getWritableDatabase();
delete this line? unnecessary with the new DAO classes and `withDatabase` helper method

2020-12-08 00:13 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
> +        ConfigActivity.dt.open();
this line is probably unnecessary with new DAO layer

2020-12-08 00:17 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
> +        StudyDao.Companion.deleteField(exp_id);
This is not equivalent to what was originally there. Orphaned records might still exist after `deleteField` is called

2020-12-08 00:50 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
> +        StudyDao.Companion.deleteField(exp_id);
never mind, just found the cascade on delete code

2020-12-08 00:59 UTC, trife commented on app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
> +        StudyDao.Companion.deleteField(exp_id);
Chaney and I talked about this a bit and ultimately decided that skipping the cascade delete and reimporting the same field as a new field with disconnected phenotypes was the safest implementation for users and would allow old phenotypes to be recovered if needed.

2020-12-08 01:06 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
> +        StudyDao.Companion.deleteField(exp_id);
Cool cool. As long as its a conscious choice and not a typo then I'm satisfied.

2020-12-08 01:27 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +class Migrator {
Consider renaming this class (or the methods inside it, or at least a comment at the top) to specifically reference Field Book DBv9. 
It looks like this class only handles the upgrade from DBv8 to DBv9 and is not prepared to handle the any future updates. So it is not a generic `Migrator` but a specific `DBv9Migrator`. You could separate the out generic methods into a parent class, but its probably not worth the effort right now. And, as @timparsons mentioned, there are DB upgrade libraries to handle this sort of thing in the future.

2020-12-08 15:47 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +                        "study_db_id" to "INT REFERENCES ${Study.tableName}(${Study.PK}) ON DELETE CASCADE",
`study_db_id` here is not actually a studyDbId, it is a studyPK (aka exp_id). 
I think the migration will be ok, but if you load a new study and try to put a BrAPI studyDbId in `observationUnit.study_db_id` the foreign key constraint will break.

2020-12-08 15:58 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +                        "study_db_id" to "INT REFERENCES ${Study.tableName}(${Study.PK}) ON DELETE CASCADE",
reading further, `study_db_id` here should be `Study.FK`. 
I still think the value of `Study.FK`should change, but at least it will be consistent across all tables

2020-12-08 16:45 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +        fun createTables(db: SQLiteDatabase, traits: ArrayList<TraitObject>) {
Why are traits passed in as an argument?
`DataHelper.getAllTraitObjects()` only exists as part of the migrate process and should probably be moved out of DataHelper into Migrator.

2020-12-08 16:51 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +                }
why is this `migrateTo` hidden down here?

2020-12-08 16:52 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +                        ObservationVariable.FK to "INT",
missing foreign key constraints?

2020-12-08 17:41 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
> +        fun randomObservation(unit: String, uniqueName: String, format: String, variableName: String, variable: String): ObservationModel = ObservationModel(mapOf(
I assume this is for testing. Delete or move to a JUnit class as test prep

2020-12-08 17:49 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitDao.kt
> +        fun getAll(): Array<ObservationUnitModel> = withDatabase { db ->
I assume this is for testing. Delete or move to a JUnit class as test prep

2020-12-08 20:48 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
>                      case 2:
Sounds good, I'll include this fix in the next commit.

2020-12-08 20:50 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
> +        if (!isTableExists("ObservationUnitProperty")) {
You're right, this shouldn't ever happen, I'll clean this up. Thanks for the catch :)

2020-12-08 20:51 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
> +        ConfigActivity.dt.open();
This one will need a bit more testing. I think we should modify the activity code to always ensure the db is open before making dao calls.

2020-12-08 20:53 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +                        "study_db_id" to "INT REFERENCES ${Study.tableName}(${Study.PK}) ON DELETE CASCADE",
Good catch, do you have a suggestion for what Study.FK should be?

2020-12-08 20:57 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +                }
The idea was to migrate all observation dependencies s.a observation variables and observation units first. I believe we would get a foreign key constraint violation otherwise.

2020-12-08 21:01 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +                        ObservationVariable.FK to "INT",
This one is tricky because its specific to a feature in FieldBook. We actually keep deleted observations, in case the user accidentally deleted their work. That being said, we could probably create a constraint and have it set to null on delete, similar to the study fk.

2020-12-08 21:04 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
> +        fun updateImage(image: Image, writeLastSyncedTime: Boolean) {
No reason here :facepalm:  Thanks for the reminder I meant to clean this function up.

2020-12-08 21:05 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
> +        internal fun selectAllRange(): Array<Map<String, Any?>>? = withDatabase { db ->
unused method

2020-12-08 21:05 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
> +        fun getRangeByIdAndPlot(firstName: String,
unused method

2020-12-08 21:11 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationVariableAttributeDao.kt
> +        fun getAll() = withDatabase { it.query(ObservationVariableAttribute.tableName).toTable() }
unused method

2020-12-08 21:47 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationVariableDao.kt
> +        fun getAllTraitsForExport(): Cursor? = withDatabase { db ->
This method never uses the `db` directly, so it doesn't need the `withDatabase` wrapper I think? Unless there is some sneaky black magic I'm not seeing.

2020-12-08 21:58 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationVariableDao.kt
> +                        val rowid = db.insert(ObservationVariableValue.tableName, null, contentValuesOf(
move this query to `ObservationVariableValueDao`

2020-12-08 22:01 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationVariableDao.kt
> +                    }
move this query to `ObservationVariableValueDao` and reference it 3 times

2020-12-08 22:02 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationVariableDao.kt
> +        fun getTraitColumnsAsString() = getAllTraits().joinToString(",")
delete unused method

2020-12-08 22:03 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationVariableValueDao.kt
> +        fun getAll() = withDatabase { it.query(ObservationVariableValue.tableName).toTable() }
delete unused method

2020-12-08 22:11 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +                    .toTypedArray()
Can you use `ObservationUnitAttributeDao.getAllNames()` here instead?

2020-12-08 22:19 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +            }")
Use a formal `Log` statement, or delete if this was just for debug

2020-12-08 22:20 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +        fun getAllStudyModels(): Array<StudyModel> = withDatabase { db ->
delete unused method

2020-12-08 22:28 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +                } else null
Consider using `toTable()` here to mirror the above `getAllFieldObjects()`. 
Then you can make a single convert model to FieldObject method and use it in both cases.

2020-12-08 23:24 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +                        whereArgs = arrayOf("$exp_id")).count)
Consider using `ObservationUnitDao.getAll()` here

2020-12-08 23:27 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +        private fun modifyDate(db: SQLiteDatabase, exp_id: Int) {
`exp_id` is never used... is this method really meant to update ALL studies?

2020-12-08 23:30 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +                        whereArgs = arrayOf("$exp_id")).count)
or even `StudyDao.getCount()`

2020-12-08 23:31 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/VisibleObservationVariableDao.kt
> +        fun getVisibleTraitObjects(): Array<ObservationVariableModel> = withDatabase { db ->
unused method

2020-12-08 23:33 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/VisibleObservationVariableDao.kt
> +        fun getDetails(trait: String): Array<ObservationVariableModel> = withDatabase { db ->
unused method

2020-12-08 23:48 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/models/ObservationUnitPropertyModel.kt
> +data class ObservationUnitPropertyModel(val map: Map<String, Any>) {
Is this class meant to be empty? I guess I don't understand the difference between `ObservationUnitProperty` and `ObservationUnitValue` ....

2020-12-08 23:58 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/traits/PercentTraitLayout.java
> +                seekBar.setMax(Integer.parseInt(getCurrentTrait().getMaximum()));
`seekBar.setMax(Integer.parseInt(max));`

2020-12-09 18:46 UTC, BrapiCoordinatorSelby commented on app/src/test/java/DatabaseBatchTest.kt
> +import com.fieldbook.tracker.database.Migrator.Companion.sImageObservationViewName
These two constants don't exist anymore... I assume they should be `sLocalImageObservationsView`

2020-12-09 18:46 UTC, BrapiCoordinatorSelby commented on app/src/test/java/DatabaseBatchTest.kt
> +                ObservationDao.getUserDetail(it)
missing parameter `plotId`

2020-12-09 18:47 UTC, BrapiCoordinatorSelby commented on app/src/test/java/DatabaseTest.kt
> +import com.fieldbook.tracker.database.Migrator.Companion.sImageObservationViewName
constants missing, should be `sLocalImageObservationsView`

2020-12-09 18:48 UTC, BrapiCoordinatorSelby commented on app/src/test/java/DatabaseTest.kt
> +import com.fieldbook.tracker.database.Migrator.Companion.sImageObservationViewName
reading further, they are unused imports and can be deleted

2020-12-09 19:15 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +                        "study_db_id" to "INT REFERENCES ${Study.tableName}(${Study.PK}) ON DELETE CASCADE",
TL;DR probably `study_id` is fine, just to keep it separate from the BrAPI specific stuff. 

My personal favorite naming scheme is to match PKs and FKs. So the Study table has PK `study.study_id` and the Obs Unit table would have the FK `obsUnit.study_id`.
My second favorite naming scheme is to FK = table + PK. So the study table has PK `study.id` and the Obs Unit table would have the FK `obsUnit.study_id`.
In this case, that would mean either `internal_id_study` or `study_internal_id_study` which are both fine but pretty wordy. 

Really my issue was only with the confusion with BrAPI fields, since there already is a `study.study_db_id` field but its not the PK, so at first glance it looks like you are matching PKs and FKs, but not really. so you could get away with `study_id` just to keep it separate from the BrAPI specific stuff and have minimal changes to the rest of your code.

2020-12-09 19:24 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +                }
My only thought is that lines 148:186 only deal with ObservationVariableAttribute and ObservationVariableValue, and Observations does not depend directly on either of those.

But this just my neurotic code tidiness talking, if it ain't broke don't fix it.

2020-12-09 19:29 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
> +                        ObservationVariable.FK to "INT",
I like DB constraints when possible cuz it stops me as a dev from doing dumb stuff (and it makes ORM libraries super helpful) but I will happily accept that it is an existing Field Book feature and don't break it. Your call.

2020-12-09 19:54 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +                    }).toInt()
Missing `count` from field object

2020-12-09 19:57 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +                        put("date_import", e.date_import)
The original code set `date_import` to the current time (see DataHelper:2019 commented code)
Either this feature should be maintained, or each calling class needs to be modified to add the import timestamp

2021-01-14 23:05 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
> +        fun updateImage(image: Image, writeLastSyncedTime: Boolean) {
@chaneylc bump

2021-01-14 23:06 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitDao.kt
> +        fun getAll(): Array<ObservationUnitModel> = withDatabase { db ->
@chaneylc bump

2021-01-14 23:14 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +        private fun modifyDate(db: SQLiteDatabase, exp_id: Int) {
@chaneylc is this method really meant to update ALL studies?
I was expecting you to use the `exp_id` in the method, not remove it

2021-01-15 16:59 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +        private fun modifyDate(db: SQLiteDatabase, exp_id: Int) {
I changed this back to only edit the selected study.

2021-01-20 19:59 UTC, merged