BrAPI Observation Syncing
PhenoApps/Field-Book pull request #513
Opened 2022-10-27 13:55 UTC by zrm22

# Description

This Pull Request will allow the user to pull down existing Observations for a BrAPI study.  This is not done automatically, but rather through a Dialog that is completely optional.  This allows for users to update fields on devices depending on what was scored on different devices

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

I have tested this for test fields stored in Breedbase pulling down ~150 observations for both BrAPI v1 and v2.  I have also tested the pagination by setting pageSize to 10 and pulling down the same study.

**Test Configuration**:
* Motorola G series phones from 2020-2022
* SDK: Recent versions of Android, unknown exactly.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [x] My changes generate no new warnings

2022-10-27 16:43 UTC, zrm22 commented
@trife @chaneylc @BrapiCoordinatorSelby One thing that I could use some guidance on.  Right now I have code in BrapiLoadDialog which will pull down the observations when the field is initially loaded, but I turned it off in favor of having the user specifically requesting for the observations to be loaded in through the BrapiSyncObsDialog.  

My question is would anyone see a use for having it pull down the observations automatically when the field is loaded in.  I can see both sides where it is less user required interaction to have it auto-load, but the user might not actually want it(and it would take the field loading process more time).

Any thoughts?  If its not useful I can clean up BrapiLoadDialog a lot.

2022-10-27 17:47 UTC, trife commented
@zrm22 I think the best pattern would be to prompt the user to sync when the field is selected. If it is possible to determine if there are unsynced observations in the background prior then this notification could be dynamically displayed to the user based on the result of that check.

2022-10-27 19:05 UTC, trife commented
Is it possible to query/filter obs or studies to get a lastEdited single timestamp and compare that instead? If we can generate an efficient query to check for new/edited obs without having to pull them all, then the user-facing popup is definitely the way to go to ensure that they know that 1) they're out of sync and 2) there's an option to get back in sync.

2022-10-27 19:07 UTC, chaneylc commented
There probably is, but I think anytime we utilize network it could be considered an expensive call. So I'd say that should require an explicit user action, like having them press the sync option.

2022-10-28 12:09 UTC, BrapiCoordinatorSelby commented
tl;dr Just a manual sync option is probably good enough for _most_ users _most_ of the time
I figured out my opinion as I was writing this. I apologize for the length, its basically my whole thought process vomited out. 


Just trying to wrap my head around the possible workflows here

1. Manual Sync Option
Open Fields list -> Tap options (three dots) on existing field -> Tap Sync -> Pop-up confirm Sync -> Observations downloaded
2. Sync on Field Select
Open Fields list -> Select existing field (radio button) -> Pop-up trait import warning -> Pop-up Confirm Sync (optional based on preferences) -> Observations downloaded
3. Auto Sync on Field Download
Import Field w/ BrAPI -> Select Field -> "Preview Field" -> Pop-up field data preview -> Observations downloaded w/ study data -> "Save"
4. Manual Sync on Field Download
Import Field w/ BrAPI -> Select Field -> "Preview Field" -> Pop-up field data preview -> study data downloaded w/o obs -> "Sync Observations?" -> Pop-up Confirm Sync (optional based on preferences) -> download observations -> "Save"

Are these the basic workflows we are talking about here? Any that I'm missing or over simplified?

After writing out this list, I think I agree with @trife , workflow number two makes a lot of sense and I don't think we need to worry about syncing on the initial study download. I also agree with @chaneylc, we don't want to make an extra HTTP call every time the user taps a new field, that will be very slow. I would also have a preference setting that allows something like "Never Sync Observations", "Always Sync Observations", or "Ask Me Every Time", to control the pop-up. "Always Sync Observations" would always attempt to sync observations when a new field is selected, which could take time, so some additional Toast or loading wheel might be a good idea to give the user some feedback.

In conclusion, workflow number one is important to keep the manual option always available, This is priority number one. 
Workflow two is optional, it might be useful to some people, but it might not be that much more useful than a manual sync. If implemented it can be controlled by a preference to allow users to decide on a flow that works best for them. 
Workflow two also necessarily occurs after new Field download, so it makes workflows three and four redundant. 
To answer the original question @zrm22, In my opinion, yes you can clean up the BrapiLoadDialog code. 

Thank you for coming to my TedTalk 😝

2022-10-28 12:54 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/brapi/BrapiLoadDialog.java
> +                    observationIds.add(obj.getExternalDbId());
I know this whole method might get removed, but this looks wrong, and other code should be checked for the same mistake.

FB Traits are BrAPI Variables, and the FB `TraitObject.ExternalDbId` is mapped to the BrAPI `Variable.observationVariableDbId`

Adding variable ids to a list of `observationIds` doesn't make sense

2022-10-28 13:49 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java
> +                System.out.println("Size of study details after sort: "+sortedPlotValues.size());
Is this necessary? It looks like `sortedPlotValues` is only used for logging

2022-10-28 13:51 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/brapi/BrapiLoadDialog.java
> +                    observationIds.add(obj.getExternalDbId());
I see my confusion now, `observationIds` should be re-named, it is a list of variable dbids passed to `getObservations()`

2022-10-28 13:54 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java
> +                System.out.println("Size of study details after sort: "+sortedPlotValues.size());
See comment above in BrAPIServiceV1

2022-10-28 13:58 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
> +            //         * @param exp_id the field identifier
why did this new method need to be created? How are other observations saved when collected in the app, or uploaded from a file?

2022-10-28 14:05 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
> +        paginationManager = BrapiPaginationManager(0, pageSize)
the constructor `BrapiPageManager(context)` should automatically load the default pageSize from preferences.

2022-10-28 14:14 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
> +        brAPIService!!.getTraits(brapiStudyDbId,
Why are you getting a new list of traits from the server? Downloading the study should have downloaded the traits already, and you have them in the FB DB. Pulling the traits from the FB DB is probably a good idea anyway, so if the user deletes a trait in app, or downloads additional ones, then you only need to sync observations for the traits actually being collected.

2022-10-28 14:15 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
> +                    observationIds.add(obj.externalDbId)
Same as comment above, `observationIds` is a confusing name and should be renamed to something like `traitIds` or `variableDbIds`

2022-10-28 14:21 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
> +    var brapiControllerResponse: BrapiControllerResponse? = null
`brapiControllerResponse` is not used in this class, delete?

2022-10-28 14:28 UTC, BrapiCoordinatorSelby requested changes
Most of the code looks good. I have a couple comments/questions to be addressed, and the workflow discussion needs to be resolved

2022-10-28 15:09 UTC, zrm22 commented on app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java
> +                System.out.println("Size of study details after sort: "+sortedPlotValues.size());
Yes, this can be removed, I will remove this in both v1 and v2.

2022-10-28 15:13 UTC, zrm22 commented on app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
> +        brAPIService!!.getTraits(brapiStudyDbId,
The reason why we load them here is because otherwise there is no guarantee that the trait which is on the server was loaded in when the study was loaded.  In our use case we sometimes need to add traits after the fields have already been scored for other traits.  We would then either need to reload the field or reload the traits and then do the observation sync.  This way it pulls everything associated with that study with a single reload.

We also rarely delete a trait from the app, just mark it as inactive.

2022-10-28 15:17 UTC, zrm22 commented on app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
> +                    observationIds.add(obj.externalDbId)
Yeah that is wrong.  I am renaming to observationVariableDbIds to match BrAPI spec.

2022-10-28 15:18 UTC, zrm22 commented on app/src/main/java/com/fieldbook/tracker/brapi/BrapiLoadDialog.java
> +                    observationIds.add(obj.getExternalDbId());
Agreed, the name is wrong.  Changing it to observationVariableDbIds to more closely match BrAPI.

2022-10-28 15:31 UTC, zrm22 commented on app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
> +    var brapiControllerResponse: BrapiControllerResponse? = null
Correct, will delete in next commit.

2022-10-28 15:42 UTC, trife commented
@zrm22 For this PR I'm satisfied with the manual syncing. We can definitely handle the optimizing the user-facing side later. Related to issue #514

2022-10-28 15:43 UTC, zrm22 commented
Re: Manual Syncing - Ok I think for now then I will leave in the code in case we need it in the future.  It likely can be further refracted as well at that time so there is no code duplication.

2022-10-28 15:49 UTC, zrm22 commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
> +            //         * @param exp_id the field identifier
Part of the reason is that this new method will check to see if there is already an observation in the DB with that id.  That being said, I should be able to convert the BrapiObserervation into a ObservationModel and just add the check to the old method.  It does look like that is not being used though currently either. 

 I can track down what the current method call is and see if we can use it here(unless @chaneylc or @trife can find it faster).

2022-10-28 15:54 UTC, zrm22 commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
> +            //         * @param exp_id the field identifier
It uses the insertUserTraits method in ObservationDao.  I think this could work as when the normal CollectActivity needs to update it will delete the observation(called Trait in the code) first and then try to load a new piece of information.  I can still put in my check to make sure we are not overwriting anything as in the normal use case there should be nothing there.

This will likely need to change once the multi-observations per plot stuff is worked out as well.

2022-10-28 16:05 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
> +        brAPIService!!.getTraits(brapiStudyDbId,
I guess this is a question of functionality. I could see a use case where I have a small set of traits i'm interested in collecting, but by syncing, suddenly I have a large number of extra traits in loaded in FB I wasn't expecting. In my use case, I would have to delete traits after syncing, in your use case you would have to add traits before syncing. I guess it comes down to which use case is more likely or happens most often, and I have no idea. @trife might have some insight here. 

Or we keep it the way you have it and see if anyone complains lol

2022-10-28 16:13 UTC, zrm22 commented on app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
> +        brAPIService!!.getTraits(brapiStudyDbId,
That makes sense.  We also do see that as the season progresses.  It's not as big an issue though as the later traits we score are 1 day and done type ones which we would not sync observations as its the only day we would need to score.

Maybe what would be more useful long term is that when you click Sync Observations it gets the traits for a given study from BrAPI -> Loads a new Dialog with check boxes for each trait -> Click Load Button -> BrAPI pulls down only selected traits for that study.

This would allow the user to select which traits are needing to be synced without relying on them to load in through the Trait Dialogs.  

This would take me a bit of time to get implemented which I honestly don't have for a month or two, but I think it solves both use cases fairly elegantly.

2022-10-28 16:14 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
> +        paginationManager = BrapiPaginationManager(0, pageSize)
oooooo I see. I tried to cast `Context` to `Activity` in the constructor and it did not like that...
if you were feeling really generous you could modify the constructor to check `if (context instanceof Activity)` and wrap it around lines 26-30. Or just leave it and use the other constructor, fine by me either way.

2022-10-28 16:17 UTC, BrapiCoordinatorSelby commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
> +            //         * @param exp_id the field identifier
I don't want to make it too complicated for you at this point, I'm just trying to avoid too many different methods accessing the DB in slightly different ways. That is how you get a corrupt DB when those methods fall out of sync. Perhaps make a new issue to address this later if it is too complex to map to one of the existing functions.

2022-10-28 16:17 UTC, zrm22 commented on app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
> +        paginationManager = BrapiPaginationManager(0, pageSize)
I will try that after I demo.  I'd rather not break it 45 minutes before I need to show it off :smile:

2022-10-28 16:20 UTC, zrm22 commented on app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
> +            //         * @param exp_id the field identifier
Yeah I agree, use the same methods as much as possible.  

I would like to take a shot at fixing it for this PR.  If it is too involved a new issue will be created.  I think it should be an easy fix, just need to make sure I map the variables in the BrAPI object to the right variables in the method.  Not hard, just need to be careful and make sure its right.

2022-10-28 16:25 UTC, BrapiCoordinatorSelby approved these changes

2022-11-04 21:50 UTC, trife commented
@zrm22 Would you willing to make issues for any of the conversations that will require additional development efforts? Going to merge this and additional changes will be part of the winter cleanup.

2022-11-04 21:50 UTC, merged

2022-11-07 14:34 UTC, zrm22 commented
@trife Yeah I can go through and make issues for the additional development efforts.  I will assign the ones I can do to myself. I might not have a chance to work until the beginning of the year, but I should be able to get some if not all of it ready before field season.  Thanks again for reviewing and accepting the code!