Hilt
PhenoApps/Field-Book pull request #537
Opened 2023-02-10 16:54 UTC by chaneylc

# Description

Introduces hilt dependency injection. Includes new themes.

Fixes #536

2023-02-24 15:35 UTC, trife commented
Had a crash when I went from Collect back to Config:
```
2023-02-24 10:24:38.199 17095-17095/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fieldbook.tracker, PID: 17095
    java.lang.RuntimeException: Unable to destroy activity {com.fieldbook.tracker/com.fieldbook.tracker.activities.CollectActivity}: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.fieldbook.tracker/databases/fieldbook.db
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5390)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5423)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.fieldbook.tracker/databases/fieldbook.db
        at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:58)
        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1388)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1264)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1432)
        at com.fieldbook.tracker.database.SqlUtilKt.query(SqlUtil.kt:53)
        at com.fieldbook.tracker.database.SqlUtilKt.query$default(SqlUtil.kt:51)
        at com.fieldbook.tracker.database.dao.ObservationDao$Companion$getAll$4.invoke(ObservationDao.kt:54)
        at com.fieldbook.tracker.database.dao.ObservationDao$Companion$getAll$4.invoke(ObservationDao.kt:52)
        at com.fieldbook.tracker.database.SqlUtilKt.withDatabase(SqlUtil.kt:166)
        at com.fieldbook.tracker.database.dao.ObservationDao$Companion.getAll(ObservationDao.kt:52)
        at com.fieldbook.tracker.database.dao.ObservationDao$Companion.getAllRepeatedValues(ObservationDao.kt:63)
        at com.fieldbook.tracker.activities.CollectActivity.refreshRepeatedValuesToolbarIndicator(CollectActivity.java:1616)
        at com.fieldbook.tracker.activities.CollectActivity.traitLayoutRefresh(CollectActivity.java:1595)
        at com.fieldbook.tracker.activities.CollectActivity.onDestroy(CollectActivity.java:687)
        at android.app.Activity.performDestroy(Activity.java:8316)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5377
```

2023-03-01 14:54 UTC, timparsons requested changes
Happy to see dependency injection being integrated into the codebase!

2023-03-01 14:54 UTC, timparsons commented on app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
> +    VerifyPersonHelper verifyPersonHelper;
Not sure the feasibility of this, but would it be possible to use constructor injection instead of field injection?  This will make the code more testable as dependencies can be created (or mocked) in a test (this comment applies to all the DI changes).

2023-03-01 16:02 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
> +    VerifyPersonHelper verifyPersonHelper;
It is possible to do constructor injection but not recommended for view classes: https://developer.android.com/training/dependency-injection/dagger-android as activities require a zero-parameter constructor. Also you can find a test in androidTest/ActivityTest that uses ActivityScenarioRule which is similar to mocking an activity, but obviously you can't test by modifying the injected fields and creating that way.

2023-03-01 16:21 UTC, timparsons commented on app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
> +    VerifyPersonHelper verifyPersonHelper;
Ah, that makes sense!

2023-03-01 16:23 UTC, timparsons approved these changes

2023-03-14 20:43 UTC, merged