Geonav shorter log
PhenoApps/Field-Book pull request #693
Opened 2023-07-31 17:47 UTC by kamathprasad9

## Description

Goenav now separately logs (```/storage/geonav_shorter/```) only the closest plant instead of logging all the plants in the field. This PR also addresses issue #659; location accuracy correction status is now being logged too.

## Type of change

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Checklist:

- [ ] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated relevant documentation

## Changelog entry

```Added separate geonav logging to capture only the closest plant```

2023-08-02 18:38 UTC, trife commented
- [ ] Save to genoav directory instead of new directory
- [ ] Setting in geonav section to specify shorter vs longer log

2023-09-12 21:22 UTC, chaneylc requested changes
Overall I think we need a brief description of what it means to be a verbose vs shorter log.

Verbose will log any location update, along with various steps in the IZ algorithm.

Shorter seems to not log location updates, and only logs the CLOSEST_FINAL obs. unit, which is the closest obs. unit to the user.

That being said, I think there should be a more meaningful naming and preference summary/description for these modes. I think verbose is fine, but shorter should be something more significant.

Verbose should be selected by default.

2023-09-12 21:22 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/preferences/GeoNavPreferencesFragment.kt
> +        geoNavLoggingMode?.isVisible = geoNavLog!!.isChecked
Avoid using "!!" and instead wrap with a null check to avoid NPE, which would crash the app.

2023-09-12 21:22 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/preferences/GeoNavPreferencesFragment.kt
> +                .putString(GeneralKeys.GEONAV_LOGGING_MODE, newValue as? String ?: "Shorter Log").apply()
Replace static strings such as "Shorter Log" with a string resource.

2023-09-12 21:22 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/utilities/GeoNavHelper.kt
> +            val currentLoggingMode = mPrefs.getString(GeneralKeys.GEONAV_LOGGING_MODE, controller.getContext().getString(R.string.pref_geonav_logging_mode)) ?: controller.getContext().getString(R.str
This is used many times throughout your PR, consider making it a function.

2023-09-12 21:22 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/utilities/GeoNavHelper.kt
> +            "start latitude, start longitude, UTC, end latitude, end longitude, azimuth, teslas, bearing, distance, fix, closest, accuracy correction status, unique id, primary id, secondary id\n"
I recently added the 'fix' header which will give a string value such as GPS, RTK within the log. It seems you're adding a numerical value that represents the accuracy in meters from internal GPS (location.accuracy). This might crash when using external devices because accuracy has not been set within the Location object. Is it necessary to show the accuracy in meters vs already knowing it is a GPS fix? If it is necessary, this will need to be updated by adding accuracy to the external Location object when external devices are used.

2023-09-12 21:22 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/utilities/GeoNavHelper.kt
> +                    val currentLoggingMode = mPrefs.getString(GeneralKeys.GEONAV_LOGGING_MODE, R.string.pref_geonav_shorter.toString())
R.string.pref_geonav_shorter.toString() will return a string representing an integer id for a resource. Use context.getString like your other preference calls.

2023-09-12 21:22 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/utilities/GeodeticUtils.kt
> +                        distance = distance, closest = NOT_CLOSEST, fix = fix, accuracyCorrectionStatus = start.accuracy)
This is what I mentioned before, start might not have accuracy, especially if its from an external source.

2023-09-12 21:22 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/utilities/GeodeticUtils.kt
> +                izLogArray.forEach { if (it.closest == 1) writeGeoNavLog(log, it.toString()) }
When testing this the log was empty. it.closest == 1 should be it.closest == CLOSEST_FINAL, which is 2. 

closest: either 0, 1, or 2.
         *      0: not closest or within the trapezoid
         *      1: updated to closest and within trapezoid
         *      2: the closest point that IZ returns
After switching to CLOSEST_FINAL, the log was working.

2023-09-15 19:20 UTC, kamathprasad9 commented
> Overall I think we need a brief description of what it means to be a verbose vs shorter log.
> That being said, I think there should be a more meaningful naming and preference summary/description for these modes. I think verbose is fine, but shorter should be something more significant.

How does this sound?:
- Verbose logs: Logs any location updates along with algorithm steps
- Closest plant logs: Logs only the closest plant to the user at a given time based on the algorithm used

2023-09-15 19:37 UTC, chaneylc commented
> > Overall I think we need a brief description of what it means to be a verbose vs shorter log.
> > That being said, I think there should be a more meaningful naming and preference summary/description for these modes. I think verbose is fine, but shorter should be something more significant.
> 
> How does this sound?:
> 
>     * Verbose logs: Logs any location updates along with algorithm steps
> 
>     * Closest plant logs: Logs only the closest plant to the user at a given time based on the algorithm used

That's good for now, just replace plant with observation unit to generalize it.

2023-09-21 13:37 UTC, chaneylc approved these changes

2023-09-25 16:50 UTC, merged