BrAPI setting enhancements
PhenoApps/Field-Book pull request #729
Opened 2023-09-13 17:40 UTC by bellerbrock

## Description

_Provide a summary of your changes including motivation and context.
If these changes fix a bug or resolves a feature request, be sure to link to that issue._

Adds checkbox to enable/disable BrAPI. Hides remaining prefs and removes BrAPI from import/export options if disabled.
Adds editable server display name to use in import/export dialogs instead of 'BrAPI'. Defaults to the server url minus scheme and subdomain.
Gives user the option to make BrAPI the default import and/or export option when a server is successfully authorized.

closes #570 and #699

## Type of change

_What type of changes does your code introduce? Put an `x` in boxes that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated relevant documentation

## Changelog entry

_Please add a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
BrAPI setting enhancements
```

2023-09-13 18:25 UTC, trife commented
@bellerbrock add a check to the server name so that if it's blank it shows "BrAPI". Are there checks for if servername returns blank?

2023-09-21 14:14 UTC, chaneylc requested changes
- [x] disable toolbar authentication if BrAPI is disabled

2023-09-21 14:14 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java
> +        String displayName = sp.getString(GeneralKeys.BRAPI_DISPLAY_NAME, getString(R.string.preferences_brapi_server_test));
In TraitEditor and Config activities you do this:
`String displayName = ep.getString(GeneralKeys.BRAPI_DISPLAY_NAME, "BrAPI");`

It seems this should be consistent and all cases should be R.string.export_source_brapi, but let me know if you did this for a specific reason.

2023-09-26 17:22 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java
> +        String displayName = sp.getString(GeneralKeys.BRAPI_DISPLAY_NAME, getString(R.string.preferences_brapi_server_test));
The idea was that when BrAPI is first enabled the url defaults to the test server, so the display name should default to the test server text. From that point forward the BRAPI_BASE_URL is always set to something, so the default can b anything, it no longer gets used. But regardless you're right it should be consistent if only for readability, I'll go ahead and unify them.

Speaking of the default display name, how do you feel about changing the `preferences_brapi_server_test` string from '**Default Test Server**' to '**BrAPI Test Server**'? I think that could help clarify things.

2023-09-26 17:32 UTC, trife commented on app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java
> +        String displayName = sp.getString(GeneralKeys.BRAPI_DISPLAY_NAME, getString(R.string.preferences_brapi_server_test));
Yeah that's fine with me

2023-09-28 17:36 UTC, trife approved these changes

2023-09-28 17:37 UTC, merged