Implementing functionality to scan a QR code with BrAPI config settings
PhenoApps/Field-Book pull request #766
Opened 2023-10-12 18:13 UTC by trife

## Description

Scans and parses a QR code containing BrAPI-specific settings

## Type of change

_What type of changes does your code introduce? Put an `x` in boxes that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated relevant documentation

## Changelog entry

_Please add a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Scans and parses a QR code containing BrAPI-specific settings
```

2023-11-01 20:22 UTC, chaneylc approved these changes
Looks good. Fixed a few minor things. My only comment is that the QR relevant code could be encapsulated into a class, instead of directly in the brapi preferences, but we can refactor this at a later point.

2023-11-06 03:41 UTC, timparsons requested changes
Two minor changes to make, otherwise looks great!

2023-11-06 03:41 UTC, timparsons commented on app/src/main/java/com/fieldbook/tracker/objects/BrAPIConfig.java
> +        return pageSize == that.pageSize && chunkSize == that.chunkSize && serverTimeoutMilli == that.serverTimeoutMilli && url.equals(that.url) && name.equals(that.name) && version.equals(that.versi
This equals method needs to be updated as it is comparing strings using `==` instead of `.equals(...)`

2023-11-06 03:41 UTC, timparsons commented on app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java
> +//        setBaseURLSummary();
Can this line be removed?

2023-11-10 17:56 UTC, timparsons approved these changes

2023-11-14 20:59 UTC, trife commented
- [ ] Add developer documentation

2023-11-15 18:15 UTC, bellerbrock commented
> * [x]  Add developer documentation

https://github.com/PhenoApps/Field-Book/wiki/BrAPI-(WIP-10-24-23)#configuration

2023-11-30 18:06 UTC, merged