Add dialog for selecting trait
PhenoApps/Field-Book pull request #811
Opened 2023-11-14 23:33 UTC by kamathprasad9

## Description

Fixes #633 
Use a dialog to pick traits instead of spinner

## Type of change

_What type of changes does your code introduce? Put an `x` in boxes that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated relevant documentation

## Changelog entry

```release-note

```

2023-11-27 13:31 UTC, trife commented
- [ ] Add neutral button "Modify" that opens the Traits activity
- [ ] Change OK button to Cancel
- [ ] Highlight currently selected trait in the list
- [ ] Left align the list items
- [ ] Wrap text (with tab indented second lines) for very long trait names

2024-02-06 03:44 UTC, trife approved these changes

2024-02-06 03:45 UTC, trife commented
I made a few minor changes and this looks good to me. It can be merged once @chaneylc reviews.

2024-02-08 18:32 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/views/TraitBoxView.kt
>                  if (controller.isCyclingTraitsAdvances()) {
Check for nullability here or try/catch this !! operator usage.

2024-02-08 18:34 UTC, chaneylc requested changes
Looks good, a few places you are using !! operator without try/catching or using null checks, please update that and I will accept.

2024-02-12 16:58 UTC, chaneylc approved these changes

2024-02-17 08:02 UTC, merged