SURFBIRD fields activity alpha implementation
PhenoApps/Field-Book pull request #823
Opened 2023-11-28 00:17 UTC by bellerbrock

## Description

_Provide a summary of your changes including motivation and context.
If these changes fix a bug or resolves a feature request, be sure to link to that issue._

Adds beta setting to use new fields workflow
Updates field list to show number of entries and use recyclerview
Adds indicator of field source to imported field list
Sorts most recently edited or imported field to the top of list
Long press on field enters selector mode that allows multiple list items to be selected
Short press outside selector mode opens individual field activity showing field name, dates, entry type and sync (if brapi), currently collected traits with phenotype counts, and collect and export buttons

## Type of change

_What type of changes does your code introduce? Put an `x` in boxes that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated relevant documentation

## Changelog entry

_Please add a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
added revamped fields activity as alpha feature
```

2023-11-28 10:27 UTC, trife commented
- [ ] resolve conflicts
- [ ] add "not yet implemented" toasts for unimplemented features

2023-11-28 10:30 UTC, trife commented
@chaneylc - pulling you into review but this isn't a fully completed feature yet since it's such a massive overhaul to the fields section of the app- I just don't want things to get too out of step as this work progresses. This review should focus more on the fields list than the per fields page- even if there are several features that still need to be added (bulk actions, etc.).

2023-11-28 20:12 UTC, bellerbrock commented
@trife for the last item on the checklist, would [this](https://gist.github.com/gabrielemariotti/4c189fb1124df4556058) be a good strategy? It's a guide on how to use a RecyclerView.Adapter with sectioned lists that was linked to from the original [contextual action bar guide](https://www.grokkingandroid.com/statelistdrawables-for-recyclerview-selection/) you shared.

2023-11-29 18:51 UTC, chaneylc commented
> * [x]  resolve conflicts
> 
>     * [x]  add "not yet implemented" toasts for unimplemented features
> 
>     * [x]  list of fields should update when navigating back after collecting a phenotype
> 
>     * [ ]  I'm not sure how the best way of implementing it (part of the recyclerview vs a separate view) for the most recent item, but it should be separated from the rest of the list like the mockup

Can we add/link the mockup here so we have it as reference?

2023-11-29 19:34 UTC, chaneylc reviewed
Looks like a good start, I added some suggestions. I was playing around with the list items and I think it would look good with background="@drawable/cell" with 8dp layout margin on the linear layout.

I know this is just a draft but I wasn't able to delete from the field editor activity, and selecting the checkboxes didn't seem to do anything. (guessing this just isn't implemented yet). 

List item obs. unit count text view looks a little odd with long field names, maybe it should be on a line below.

Using the field book launcher icon is kinda cool but it doesn't work well with the high contrast theme.

[edit] for reference, I have only reviewed new field editor / field adapter mainly.

2023-11-29 19:34 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/adapters/FieldAdapter.java
> +        }
You should use the viewType parameter in on createViewHolder.

I suggest creating an enum for these: csv, xls, brapi, etc... then use inheritance to create subtypes for each where they have a reference to the enum. Then in onCreateViewHolder you can just match the enum's ordinal value to the viewType parameter.

2023-11-29 19:34 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/adapters/FieldAdapter.java
> +public class FieldAdapter extends RecyclerView.Adapter<FieldAdapter.ViewHolder> {
I suggest switching your super type to ListAdapter. It automatically checks for list item differences on a background thread. You will need to implement a DiffCallback, which helps show how the list items are different. This will simplify the implementation a bit, and you won't have to manage ArrayList<FieldObject> list. Your controller will pass the list via adapter.submitList() and your class will have a public getCurrentList() that you can access.

2023-11-29 19:34 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/adapters/FieldAdapter.java
> +public class FieldAdapter extends RecyclerView.Adapter<FieldAdapter.ViewHolder> {
Also. This may be vestigial from old implementations, but you should try to only have one reference of the ListAdapter in FieldEditorActivity, (right now it is re-instantiated every time loadData is called). The above comment will make this a lot easier, whenever you update the data just send it to submitList.

2023-11-29 19:34 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +            val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
This should probably be put in SqlUtil.kt and kept consistent with getTime() which is used for studies.

2023-11-29 19:34 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
> +                        val traitName = cursor.getString(cursor.getColumnIndexOrThrow("observation_variable_name"))
Might want to try/catch this or use the other signature that returns -1

2023-11-29 20:25 UTC, bellerbrock commented
Hey Chaney, thanks for taking a look and providing feedback.

Some of the features you're seeing sound like they're from an outdated version of the branch - the checkboxes and field book launcher were experiments I later got rid of. The obs unit count should be on the line below in the latest version.

You're right, the batch delete, archive and export features are are work in progress. At this point you should just see a toast when you press them.

Part of the implementation process will be adding sections to the field adapter recyclerview, so that archived trials can be moved to the last section (which will be collapsed by default). Do you have any recommendations on how best to implement the sections? Trevor and I discussed a bit yesterday and I found [this](https://gist.github.com/gabrielemariotti/4c189fb1124df4556058) (possibly outdated) guide, but we thought you might have the most insight.

2023-11-29 20:28 UTC, chaneylc commented
> Part of the implementation process will be adding sections to the field adapter recyclerview, so that archived trials can be moved to the last section (which will be collapsed by default). Do you have any recommendations on how best to implement the sections? Trevor and I discussed a bit yesterday and I found [this](https://gist.github.com/gabrielemariotti/4c189fb1124df4556058) (possibly outdated) guide, but we thought you might have the most insight.

I would create two recycler views, active and archived. Wrap them in linear layouts with title text views above them.

2024-01-18 22:50 UTC, trife commented
- [ ] When sync is hidden the white space needs to also be hidden- currently the gap between export/data is unbalanced when sync is missing
- [ ] When in "selector mode" and the toolbar back button or an action button is pressed, it should exit "selector mode"- currently remains in selector mode

2024-01-27 02:51 UTC, trife commented
- [ ] sort order in field details not updated when sort is changed

2024-02-06 18:22 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/activities/FieldDetailFragment.kt
> +                    showEditNameDialog()
Need to be careful here. This name is used in the export file, so users can input special characters here and break the export. Characters should be limited to whats allowable in the file system.

Also this FieldEditorActivity needs to update the list when navigating back from the specific field page, currently it shows the old field name after editting.

2024-02-06 19:13 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/activities/FieldDetailFragment.kt
> +    fun collectDataFilePermission() {
Talked with @trife, implementation is fine as is.

2024-02-07 19:09 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/activities/FieldDetailFragment.kt
> +        }
Agreed, I had changed it the the generic 'edit field' when Trevor pointed out that we would add more editable things to the dialog like location and barcode search column. But those will be added later, so I've made it more descriptive for now.

2024-02-07 19:16 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/adapters/FieldAdapter.java
> +        }
Yeah, I considered that, but couldn't think of a better way to handle it unless/until brapi provides both singular and plural versions of the observation levels.

2024-02-07 19:33 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/activities/FieldDetailFragment.kt
> +        val narrativeString = getString(R.string.field_detail_narrative, exp_source, field.count, observationLevel, field.attribute_count, sortOrder)
I looked at a few ways of doing this, and it seemed that while getText() lets you apply simpler styling to the resource string it doesn't support placeholder substitution. In the end [this example](https://developer.android.com/guide/topics/resources/string-resource.html#formatting-strings) from the android developer docs seemed like the best fit so I followed it.

2024-02-07 19:43 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/activities/FieldDetailFragment.kt
> +    fun formatSemanticDateForDisplay(dateStr: String?): String {
Yeah I definitely see the advantage of that. For some reason I was thinking it'd be best not to pass the context if it wasn't necessary, but into retrospect it seems pretty necessary to avoid code duplication if we want to use the util more than once 😂

2024-02-08 19:44 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/activities/brapi/BrapiExportActivity.java
> +                }
complete with a8b0c5dfdb6f0541891b24c867c689b8bdebabd7

2024-02-08 19:50 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
>      private Menu systemMenu;
will do. I see that update is also an open pr, so will have to wait to resolve this once one or the other is merged

2024-02-08 20:20 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
>      Handler mHandler = new Handler();
fixed by c3e97a6d0590f850c4cd50aef79140c0f0ba77c9

2024-02-08 23:25 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/activities/FieldDetailFragment.kt
> +
fixed with 8c9cfd52766dd79deb57d7bdc087e294ab8c1927. I looked at the summary fragment and saw how it has direct access to the collect activity's studyId. Used the same strategy since it seems simplest and seems fine to have the FieldDetailFragment coupled to the FieldEditorActivity, but if there are other reasons to use intent extras let me know.

2024-02-09 00:01 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/activities/FieldDetailFragment.kt
> +            cardViewSync.visibility = View.VISIBLE
implemented in 6341109e3bf23d2d5272e70ebc33eb8fe764f324

2024-02-09 22:31 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/activities/FieldDetailFragment.kt
> +    fun formatSemanticDateForDisplay(dateStr: String?): String {
implemented in 42d7f332cddd23084ee416d13408efdb4d827b61

2024-02-10 03:22 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/adapters/FieldAdapter.java
> +public class FieldAdapter extends RecyclerView.Adapter<FieldAdapter.ViewHolder> {
completed in 2a5f63138e21d15beab107aa498783e6aca92302

2024-02-15 00:04 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/activities/FieldEditorActivity.java
> +        implements FieldSortController, FieldAdapterController, FieldAdapter.OnFieldSelectedListener, FieldAdapter.AdapterCallback {
I've added an indicator with this commit - 24350c1ab0b3dd4160c3dd5259b1615f7c439e88

I wasn't sure what the best approach would be considering the existing on-click behaviors and future field workflow changes, but let me know what you think.

2024-02-17 09:04 UTC, trife commented
- [ ] When importing a new field, the indicator doesn't update- instead there end up being two active indicators
- [ ] With the sample data imported, the dates in the field page are not updating when new data is collected
- [ ] Renaming a file doesn't update when going back to list of fields
- [ ] @chaneylc - do you think we should force (re)names to be unique? 
- [ ] New field creator is broken when individual pages is enabled
- [ ] Make sure active field indicator is visible on eInk
- [ ] I'm getting crashes with this both when exporting and importing when the individual field pages are enabled. This is only using sample data files and not loading data when the app starts.

Export:
```
FATAL EXCEPTION: main
                                                                                                    Process: com.fieldbook.tracker, PID: 9601
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.fieldbook.tracker.objects.FieldObject.getExp_name()' on a null object reference
                                                                                                    	at com.fieldbook.tracker.utilities.ExportUtil.exportLocal(ExportUtil.kt:226)
                                                                                                    	at com.fieldbook.tracker.utilities.ExportUtil.exportPermission(ExportUtil.kt:117)
                                                                                                    	at com.fieldbook.tracker.utilities.ExportUtil.export(ExportUtil.kt:94)
                                                                                                    	at com.fieldbook.tracker.utilities.ExportUtil.exportActiveField(ExportUtil.kt:81)
                                                                                                    	at com.fieldbook.tracker.activities.FieldDetailFragment.onCreateView$lambda$4(FieldDetailFragment.kt:131)
                                                                                                    	at com.fieldbook.tracker.activities.FieldDetailFragment.$r8$lambda$6nmxbuNAJJEkbUFIgdV05qo4a4U(Unknown Source:0)
                                                                                                    	at com.fieldbook.tracker.activities.FieldDetailFragment$$ExternalSyntheticLambda4.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7658)
                                                                                                    	at android.view.View.performClickInternal(View.java:7635)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:30167)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8248)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

Import:
```
FATAL EXCEPTION: main
                                                                                                    Process: com.fieldbook.tracker, PID: 10643
                                                                                                    java.lang.NumberFormatException: For input string: "--1"
                                                                                                    	at java.lang.Integer.parseInt(Integer.java:797)
                                                                                                    	at java.lang.Integer.parseInt(Integer.java:915)
                                                                                                    	at com.fieldbook.tracker.database.dao.StudyDao$Companion$deleteField$1.invoke(StudyDao.kt:111)
                                                                                                    	at com.fieldbook.tracker.database.dao.StudyDao$Companion$deleteField$1.invoke(StudyDao.kt:103)
                                                                                                    	at com.fieldbook.tracker.database.SqlUtilKt.withDatabase(SqlUtil.kt:166)
                                                                                                    	at com.fieldbook.tracker.database.dao.StudyDao$Companion.deleteField(StudyDao.kt:103)
                                                                                                    	at com.fieldbook.tracker.database.DataHelper.deleteField(DataHelper.java:2198)
                                                                                                    	at com.fieldbook.tracker.async.ImportRunnableTask.onPostExecute(ImportRunnableTask.java:219)
                                                                                                    	at com.fieldbook.tracker.async.ImportRunnableTask.onPostExecute(ImportRunnableTask.java:24)
                                                                                                    	at android.os.AsyncTask.finish(AsyncTask.java:771)
                                                                                                    	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
                                                                                                    	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8248)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

2024-02-20 22:37 UTC, bellerbrock commented
@trife Thanks for your review, I pushed commits to address everything in the checklist other than the renaming question, so it should be ready for another look.

When I tested the active field indicator on eink it shows up ok, but isn't very distinct from the action mode selection, so I've added an outline to it in the latest commit. Let me know if that looks alright or if there's a better solution.

![new_active_field_indicator](https://github.com/PhenoApps/Field-Book/assets/11297346/500150f1-d216-407a-8051-69b37c45a789)

I wasn't able to test it in high-contrast mode, though I think it'd be the same since it doesn't use color. Seems like there are a few bugs in the latest build that have been pulled into this branch - I'm not able to switch themes, and advancing entry on the collect screen returns to the first trait regardless of settings.

2024-02-21 05:25 UTC, trife commented
@chaneylc could some of those bugs be related to the preferences merge?

2024-02-21 17:33 UTC, chaneylc commented
> @chaneylc could some of those bugs be related to the preferences merge?
It's possible I missed something, or something happened during merging. Preferences should now all be accessed through: 
```
PreferenceManager.getDefaulSharedPreferences(context)
```
or use the injected preferences which does that line automatically.

>  @chaneylc - do you think we should force (re)names to be unique?
If renames are only used in the frontend, they don't need to be unique. I do see how that could be come confusing though. It might be useful to have a feature that restores the original name.

2024-02-21 21:01 UTC, bellerbrock commented
Looks like [ThemedActivity.kt](https://github.com/PhenoApps/Field-Book/blob/main/app/src/main/java/com/fieldbook/tracker/activities/ThemedActivity.kt) at least is still accessing the wrong prefs file - logcat shows `Applying theme 0 to PreferencesActivity`  when the default prefs file has `<string name="key_preferences_theme_theme">1</string>`. I'll put together a PR with a fix if one of you can review it.

2024-02-26 20:19 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/adapters/FieldAdapter.java
> +        }
@chaneylc Just saw that Tim implemented a more sophisticated solution to this same problem [here](https://github.com/PhenoApps/Field-Book/blob/f61bb0bc6109dc134bc70b13f69b566f3773a6ab/app/src/main/java/com/fieldbook/tracker/brapi/BrapiLoadDialog.java#L105). What do you think, should I move the function to a util so it can be used throughout the app?

2024-02-27 15:02 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/adapters/FieldAdapter.java
> +        }
Might be best to find a library that handles all possibilities.

2024-02-28 21:22 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/adapters/FieldAdapter.java
> +        }
Hmm, I spent time time working on a solution using MessageFormat with ICU's plural rules, but it'd still require providing proper forms for possible levels in a properties file. In the end I [reworked the strings to simplify the narrative string definition and remove the need for pluralization](https://github.com/PhenoApps/Field-Book/pull/823/commits/70428625cc5fe6555c4589dc0a6a4b25a331d80f), let me know if that seems reasonable

2024-03-04 22:13 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/activities/FieldDetailFragment.kt
> +                    showEditNameDialog()
Added sanitizing in [6b3c851](https://github.com/PhenoApps/Field-Book/pull/823/commits/6b3c8512264d4dfc0fab12b7c13d3810f553c6a7)

2024-03-04 22:15 UTC, bellerbrock commented
@chaneylc @trife Just pushed a commit to resolve the last issue from chaney's review.

2024-03-14 15:26 UTC, chaneylc commented
After loading samples on a fresh install I get this crash/stacktrace:
```
(1) no such table: studies in "SELECT 
                                                                                                                        Studies.*,
                                                                                                                        (SELECT COUNT(*) FROM observation_units_attributes WHERE study_id = Studies.internal_id_study) AS attribute_count,
                                                                                                            
```

2024-03-14 15:31 UTC, chaneylc commented
When exporting multiple fields, it exports a zip file with the files, but also exports the files next to the zip file, so you get double of everything.

2024-03-14 15:46 UTC, chaneylc commented
Other than the bugs I pointed out I think it looks great and is ready.

At first I didn't know you could click the icon to switch field, but was happy to discover that. Maybe there is a way we can make that more apparent. 

These are separate issues, but also noticing that the sort dialog doesn't have a title, and the export dialog title is really small.

2024-03-14 15:51 UTC, trife commented
Fixing sort dialog is part of #872 
We're slowly working toward a more linear workflow where switching won't be as important

2024-03-14 15:51 UTC, chaneylc commented
I think it's a little odd that exporting switches field, but I get why it is like that. I'm thinking if you have field A selected, and want to export B, then A should be switched back to after the export.

2024-03-14 16:08 UTC, chaneylc commented
I think this PR will fix https://github.com/PhenoApps/Field-Book/pull/905 because you will no longer be able to sync a field that isn't imported from brapi.

Might want to add an additional check to see if brapi is enabled before attempting the sync on brapi fields. I noticed it still tried even though I disabled it in settings.

2024-03-14 16:22 UTC, chaneylc requested changes
Requesting changes for the bugs/comments I posted.

2024-03-19 19:07 UTC, bellerbrock commented
> When exporting multiple fields, it exports a zip file with the files, but also exports the files next to the zip file, so you get double of everything.

I was thinking of this as a feature - the zip file is the only one offered for sharing, but if you want to browse the field_export dir and search your exported fields later then you see individual field files without having to extract generically-named zips.

2024-03-19 19:36 UTC, chaneylc commented
> > When exporting multiple fields, it exports a zip file with the files, but also exports the files next to the zip file, so you get double of everything.
> 
> I was thinking of this as a feature - the zip file is the only one offered for sharing, but if you want to browse the field_export dir and search your exported fields later then you see the individual field files without having to extract generically-named zips.

Ok, that makes sense, just wanted to make sure it wasn't a bug.

2024-03-26 16:12 UTC, chaneylc commented
- [ ] when surfbird is enabled, should export/collect be removed from config?
- [ ] when editing field display name, I think this should show the edited name and not the original after it has been edited
- [ ] should export really switch fields?
@trife @bellerbrock these are my final notes for the PR

2024-03-26 16:17 UTC, trife commented
First point will happen as we evolve SURFBIRD from alpha. Last two points are valid and need addressed. I haven't gone through this myself yet, though.

2024-03-26 17:15 UTC, chaneylc commented
> @chaneylc I modified the export to not activate the field. Can you clarify where you are referring to with this comment? - `when editing field display name, I think this should show the edited name and not the original after it has been edited`

Sure, say I have a field named A, if I edit the display name and change it to B, the next time I try to edit it shows A, when I think it should show B.

2024-03-26 17:47 UTC, bellerbrock commented
Gotcha. Ok, show be good to go now. I agree with your first suggestion but will leave it for the next iteration of SURFBIRD features.

2024-03-26 18:57 UTC, chaneylc approved these changes

2024-03-27 17:50 UTC, merged