Updated search UI and changed search activity to dialog
PhenoApps/Field-Book pull request #825
Opened 2023-11-29 14:13 UTC by akshat22

## Description

- Changed search activity to a dialog #503 
- Updated search UI #806 
- Displaying selected attributes in the search results dialog #161 

## Type of change

_What type of changes does your code introduce? Put an `x` in boxes that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated relevant documentation

## Changelog entry

_Please add a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

2023-12-19 10:10 UTC, trife commented
@akshat22 I think this is looking pretty good. I think the big leftovers here are to clean up the logic to ensure that queries accurately return results and then to work on improving the results page. What might make sense is to custom build the results page based only on the fields used in the querybuilder. Blank values could just be a global match.

For design, it would be good to have the builder/results take a pageview approach so that the user could go back to the query builder from the results. Something similar to the new trait creator.

2023-12-21 16:02 UTC, chaneylc requested changes
Great job on using existing code and utilizing good Android patterns for creating adapters to solve this. I added a fewrequested changes. It's important we update the business logic of the searching, its very outdated. Also, I'm not sure if this is an AS bug or what, but I can't checkout your latest commits, and only receive the ones from Nov 8th. So I can't test this or actually view the changes, but the PR does show the code changes so I was able to review that.

2024-02-06 02:10 UTC, trife commented
@akshat22 This is looking really great! Notes:

- [ ] Increase minimum height of results dialog by 30%
- [ ] If selected columns are duplicates of the primary/secondary, don't add them to the results dialog (e.g. row/plot from the sample data)
- [ ] Replace the custom layouts with AlertDialogs (#872)
- [ ] Increase search dialog height by 25%
- [ ] Right justify text in querybuilder edittexts

2024-02-17 08:24 UTC, trife commented
@akshat22 - few other things I noticed or think should be changed in the most recent version:

- [ ] The defined query should always be saved until the user clears it. It looks like currently the behavior is to clear on 'Close'
- [ ] If the user navigated to an entry from the results page, open the results page when they reopen search
- [ ] Move the 'Back' button on results page to the Neutral spot
- [ ] Remove the reset circle button and add a 'Clear' Neutral button to the Search dialog
- [ ] Rename 'OK' on search dialog to 'Search'
- [ ] Add 4dp padding to top/bottom of search result entries to make them easier to press
- [ ] I'm not sure what the text size is set to in the results, but you should choose one that's dynamically defined from the theme sizes
- [ ] Don't close the search dialog if there are no results
- [ ] Remove right side scroll bar from search results- not sure about other people but I always end up accidentally pressing this
- [ ] Not sure how easy this is... potentially get rid of black lines between search results and use alternating white/grey shades to demarcate every other row. If there isn't an easy way to implement, just let me know

2024-02-26 21:03 UTC, chaneylc requested changes

2024-02-26 21:03 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/dialogs/SearchDialog.java
> +    }
If we are going to follow this strategy it should be refactored into a query builder class that is a dependency of data helper or the obs. unit. property dao. I think it would be a powerful addition to implement sqlite EXCEPT to go along with the INTERSECT operator.

2024-02-26 21:03 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/dialogs/SearchDialog.java
> +                dialog.dismiss();
Replace this static variable usage with an interface

2024-02-26 21:35 UTC, akshat22 commented on app/src/main/java/com/fieldbook/tracker/dialogs/SearchDialog.java
> +    }
What will be the use of EXCEPT here? Is it to replace INTERSECT like `C = A EXCEPT B; Solution = A EXCEPT C`?

2024-03-08 19:16 UTC, trife commented
This looks great!!! If you resolve the conflicts I can get it merged in after Chaney reviews.

2024-03-08 19:17 UTC, trife approved these changes

2024-03-12 00:01 UTC, chaneylc approved these changes

2024-03-12 11:14 UTC, merged