Adds a new Statistics Page
PhenoApps/Field-Book pull request #940
Opened 2024-03-25 22:00 UTC by akshat22

## Description

Adds a new statistics page #871 to Field Book with the following features:

- Displays multiple stats divided into season cards.
- Ability to toggle between year and month view.
- Display additional context on individual stats via dialogs and toast messages.
- Ability to export individual cards as an image with a Field Book logo by long-pressing the card.
- Display a calendar style heatmap for the number of observations collected on each day.

## Type of change

_What type of changes does your code introduce? Put an `x` in boxes that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Checklist:

- [ ] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated relevant documentation

## Changelog entry

_Please add a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Added a new statistics page to display summary of collected data.
```

2024-03-26 17:20 UTC, chaneylc commented
First of all this looks awesome!

- [ ] Replace snackbar message with a share button on each card, alternatively it could be a toolbar button and allow the cards to be selectable.
- [ ] I noticed the statistics_card.xml is fairly complicated, I think you can use grid layout manager / recycler view / adapter pattern here where you define view holders for each stat type, so it's easier to add/adjust stats in the future.
- [ ] image count is only based on "photo", this will only count images captured on the device camera, there are other photo formats like go pro and usb that won't be counted. For now update your logic with the offbeat Formats enum.
- [ ] declare a threshold variable (30) for your total interval check
- [ ] static strings should be replaced with resources
- [ ] Since the stat processing time scales with the amount of data in the database, the activity should start with some sort of "loading stats..." UI while the data processes in the background. I found with large databases it takes a while for the screen to appear after clicking Statistics.
- [ ] @trife do you want this feature wrapped in alpha/beta settings?

2024-03-26 17:20 UTC, chaneylc requested changes
See above comment for requested changes.

2024-03-28 21:14 UTC, trife commented
@akshat22 for the heatmap, you're going to need to either use the [heatmap composable](https://github.com/kizitonwose/Calendar/blob/main/docs/Compose.md#heatmap-calendar) or adapt one of the [vertical scrolling calendar views](https://github.com/kizitonwose/Calendar/blob/main/sample/src/main/java/com/kizitonwose/calendar/sample/view/Example2Fragment.kt).

2024-04-03 22:54 UTC, trife commented
- [ ] Replace the export icon with [this one](https://pictogrammers.com/library/mdi/icon/share/)
- [ ] Mostly out of curiosity to see how it looks: set the titles of the stat elements to hidden
- [ ] Make sure you use one of the available Field Book text styles for the textviews in this PR
- [ ] [Cancel previous toast](https://stackoverflow.com/questions/10070108/can-i-cancel-previous-toast-when-i-want-to-show-an-other-toast) before showing new ones
- [ ] Toast text changes: Entries: "...entries have been phenotyped"; Data: "...observations have been collected"; Time: "...hours spent phenotyping"; Photos: "...photos have been captured"
- [ ] Dialog title changes: "Fields imported in YYYY", use unique ID for title of Most dialog
- [ ] Month view needs a loading dialog while it processes
- [ ] Use month names instead of numbers (e.g. 2024 February)
- [ ] How difficult is it to stylize the exported card? It might be good to change the top line of the images to "<FB ICON> Field Book Stats for February 2024"
- [ ] Should we use a tablayout for the stats with "Total", "By Year", and "By Month" tabs? If this sounds good, add a new total section, swap the heatmap/date icons, and remove the date swap feature from the toolbar.
- [ ] Heatmap: Add toolbar buttons to move calendar to the [first day with obs](https://pictogrammers.com/library/mdi/icon/format-vertical-align-top/), [last day with obs](https://pictogrammers.com/library/mdi/icon/format-vertical-align-bottom/), and [select a date range](https://pictogrammers.com/library/mdi/icon/calendar-range/)
- [ ] Add date range picker that filters calendar view to specified dates
- [ ] Add the [counter icon](https://pictogrammers.com/library/mdi/icon/counter/) to the heatmap toolbar: when clicked it swaps the day number in the calendar for the number of observations collected that day

2024-04-25 19:15 UTC, chaneylc commented
The Config Activity Fields icon is different, is that on purpose?

Tried to select a date range, I think it crashes if you only have one date:
```
FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: com.fieldbook.tracker.debug, PID: 26100
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.Calendar.get(int)' on a null object reference
                                                                                                    	at com.fieldbook.tracker.dialogs.DateRangePickerDialog.lambda$onCreateDialog$0$com-fieldbook-tracker-dialogs-DateRangePickerDialog(DateRangePickerDialog.java:60)
                                                                                                    	at com.fieldbook.tracker.dialogs.DateRangePickerDialog$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
                                                                                                    	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

2024-04-25 19:28 UTC, chaneylc requested changes

2024-04-25 19:28 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/activities/StatisticsActivity.java
> +    private int toggleVariable = 0; // 0: Total, 1: Year, 2: Month
I think it would be best to define an enum here

2024-04-25 19:28 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/adapters/StatisticsAdapter.java
> +        if (cardTitle.length() == 7) {
I think you can use ReyclerView ViewTypes to solve this in a more modular way. 

reference: https://stackoverflow.com/questions/26245139/how-to-create-recyclerview-with-multiple-view-types

2024-04-25 19:28 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/dialogs/StatisticsCalendarFragment.java
> +    private static final String TIME_STAMP_PATTERN = "yyyy-MM-dd HH:mm:ss.SSSZZZZZ";
You can reference this in SqlUtil.kt

2024-04-25 19:28 UTC, chaneylc commented on app/src/main/java/com/fieldbook/tracker/dialogs/StatisticsCalendarFragment.java
> +        }
These should be theme attributes. Threshold value magic numbers should be defined as constants.

2024-04-25 19:35 UTC, akshat22 commented
> The Config Activity Fields icon is different, is that on purpose?

@chaneylc This is in reference to one of Trevor's notes in the previous comment to switch the icons for Fields and Plots.

> Tried to select a date range, I think it crashes if you only have one date:

Noted, will fix this.

2024-08-03 06:37 UTC, trife commented
I've changed the target to fields_modifications which is going to be our base v6 version where this will be released. I have a few minor requests for updates to close this out and get it merged:

- [ ] Swap back to the old fields icon in both the Statistics and ConfigActivity
- [ ] Use [this](https://pictogrammers.com/library/mdi/icon/view-grid-compact/) for the entries icon in Statistics
- [ ] Heatmap currently doesn't work- I'm just seeing static purple for each of the dates

2024-09-13 20:03 UTC, trife approved these changes

2024-11-07 22:12 UTC, chaneylc approved these changes

2024-11-17 09:58 UTC, trife commented
@chaneylc it looks your implementation crashes if the images don't exist on the device. I'll send you a database to test with to recreate the issue.

2024-11-22 11:32 UTC, merged