Fields modifications including trait statistics graphs
PhenoApps/Field-Book pull request #985
Opened 2024-06-10 20:36 UTC by bellerbrock

## Description

_Provide a summary of your changes including motivation and context.
If these changes fix a bug or resolves a feature request, be sure to link to that issue._

Closes #178
Closes #960

## Type of change

_What type of changes does your code introduce? Put an `x` in boxes that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated relevant documentation

## Changelog entry

_Please add a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Added trait statistics graphs to field detail page
```

2024-06-19 17:17 UTC, chaneylc requested changes
This is looking really awesome, great work! I've made some minor comments and one semi-major comment. I understand some of my comments might be a limitation of the library. For example of creating a Chartable interface using the Formats class, check out the offbeat camera PR and look at coders and value presenters.

2024-06-25 17:24 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/charts/HistogramChartHelper.kt
> +        chart.setNoDataText("No data available")
[147ad13](https://github.com/PhenoApps/Field-Book/pull/985/commits/147ad1397086ab35dd6f82f5d60ea9dded37c650)

2024-06-25 17:24 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/charts/HistogramChartHelper.kt
> +        val binSize = range.divide(BigDecimal(binCount), BigDecimal.ROUND_UP)
[147ad13](https://github.com/PhenoApps/Field-Book/pull/985/commits/147ad1397086ab35dd6f82f5d60ea9dded37c650)

2024-06-25 17:25 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/charts/HistogramChartHelper.kt
> +        val dataSet = BarDataSet(entries, "Observations")
[147ad13](https://github.com/PhenoApps/Field-Book/pull/985/commits/147ad1397086ab35dd6f82f5d60ea9dded37c650)

2024-06-25 17:25 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/charts/BarChartHelper.kt
> +        chart.setNoDataText("No data available")
[147ad13](https://github.com/PhenoApps/Field-Book/pull/985/commits/147ad1397086ab35dd6f82f5d60ea9dded37c650)

2024-07-12 21:25 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/charts/HistogramChartHelper.kt
> +        for (observation in observations) {
I tested a bit but couldn't find exactValueInt(), you mean toIntExact()? In any case yeah i think toInt() has been fine precision in all the testing I've done.

2024-07-12 21:25 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/charts/HistogramChartHelper.kt
> +object HistogramChartHelper {
fixed [4988313](https://github.com/PhenoApps/Field-Book/pull/985/commits/4988313e6586dac089d898213c407be5264b8b13)

2024-07-12 21:26 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/charts/BarChartHelper.kt
> +object BarChartHelper {
fixed with [fbf7116](https://github.com/PhenoApps/Field-Book/pull/985/commits/fbf711698298bbc0bf22a711b0e8b61abcedc45f) and [0897a99](https://github.com/PhenoApps/Field-Book/pull/985/commits/0897a99f3e600089b1f0396111454c08c020f3f9)

2024-07-12 21:27 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/charts/HistogramChartHelper.kt
> +object HistogramChartHelper {
fixed [4988313](https://github.com/PhenoApps/Field-Book/pull/985/commits/4988313e6586dac089d898213c407be5264b8b13)

2024-07-12 21:28 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/charts/HistogramChartHelper.kt
> +        val binCount = minOf(10, distinctValuesCount)
10 was based on a typical pixel screen size. I added a more sophisicated bincount determination here [a10ee20](https://github.com/PhenoApps/Field-Book/pull/985/commits/a10ee205fec25de20b2c4d5b859131e193d34afc), the max is now based on a constant min bin width and on the device metrics.

2024-07-12 21:33 UTC, bellerbrock commented on app/src/main/java/com/fieldbook/tracker/adapters/FieldDetailAdapter.kt
>      override fun onBindViewHolder(holder: ViewHolder, position: Int) {
That makes sense, the list of format strings works but certianly doesn't seem ideal for maintaining longer term. 

What do you think about merging it as is, then implementing the approach you have in mind as part of the offbeat improvements?

2024-07-12 21:36 UTC, bellerbrock commented
@chaneylc Thanks for your feedback. Should all be adressed now, other than the trait encapsulation question. I also added some additional fixes and improvements, now it's ready for another review!

2024-08-01 07:29 UTC, trife commented
- [ ] Use same sort icon on fields list as in field details
- [ ] Sort by most recent first in the fields list for all date choices and auto scroll to the top after sorting (looks like sorting by date may be messed up right now- sending you a db)
- [ ] Move the sync icon to the left of the card
- [ ] Add [icon](https://pictogrammers.com/library/mdi/icon/chart-bar/) for Data card
- [ ] Add [icon](https://pictogrammers.com/library/mdi/icon/land-fields/) for top card
- [ ] Reduce overall `LinearLayout` padding in field details fragment from 16dp to 8dp
- [ ] Modify Data card to be collapsible. Collapsed card shows num traits and obs as [chips](https://m2.material.io/components/chips/android#using-chips) on the same line. Expanded card displays and expands all graphs.
- [ ] Replace narrative in top card with [chips](https://m2.material.io/components/chips/android#using-chips). Add icons to chips to make up for missing words (sort, file, [entries](https://pictogrammers.com/library/mdi/icon/dots-grid/), [attributes](https://pictogrammers.com/library/mdi/icon/information-outline/))

2024-08-06 08:08 UTC, trife commented
- [ ] Switch back to appcompat - materialcomponents breaks a lot of the UI (e.g. all dialog boxes now have white text, all buttons in collect are green, etc.). If this means we can't stylize chips right now on a per theme basis, that's fine. But we should probably make an issue to move from appcompat to materialcomponents. Potentially can use a [bridge theme](https://m2.material.io/develop/android/docs/getting-started) to fix this. 
- [ ] Should chips have color (accent or main)?
- [ ] Use a single chip group in top card
- [ ] Hide chip if non-configured/empty (i.e. sort) or zero data (i.e. observations)
- [ ] [Traits icon](https://pictogrammers.com/library/mdi/icon/ruler/)
- [ ] [Observations icon](https://pictogrammers.com/library/mdi/icon/eye/)
- [ ] Thoughts about moving the toolbar features to on chip clicks? Non action clicks could have a toast with a verbose explanation of their info (e.g. 5 field attributes). If we do this we should sort chips to have actions at the end of the list
- [ ] For padding- revert everything back to what it was except the very most outer linearlayout

2024-08-06 17:32 UTC, bellerbrock commented
I set the observations chjp to be hidden if there are no observations, but I'm thinking the sort chip should always be visible - brapi fields now require selecting a sort order on import, and its helpful to specify that local fields are ordered the same as the import file if not explictly sorted. Though maybe the file import should also require setting the sort order on import?

I like the idea of moving the sort and rename toolbar tools to on click behavior of the relevant chips. When I see chips I'd expect them to act like buttons.  The trait count chip would then be the logical way to open the field-specific trait activity, and yeah for the other chips would be good for the on click behavior to at least show some additional info. 

I could also see an argument for converting the collect, export, and sync cards into chips within the first card, making use of the chip secondary label to show the date.

2024-08-06 18:01 UTC, trife commented
Let's go ahead and move the rename and sort actions to the chip and keep them always visible. Sort can have the text "Import order" if the field hasn't been actively sorted. For many of the files, we don't technically have a way to programmatically sort them to get them to that order (#942). 

Let's keep chips for dialogs and list items for activities that exit the field detail page. Export/Sync both have updates planned that will move them into the latter category so they both get to stay as list items for now (#662, #982). For Data, move the chips under the title but still keep them visible when it's collapsed.

2024-08-07 19:56 UTC, bellerbrock commented
> How are traits sorted in Data? Should we sort by percent complete?

They're sorted the same way as in the collect and traits activity. I'm thinking that's probably the expected order.

2024-08-08 17:21 UTC, trife commented
Changes based on external review:

- [ ] Let's treat active chips like buttons instead of informational so it's more clear what they do. Fixed text for 'Rename' and 'Sort'
- [ ] For graphs, how difficult is it to add 'Count' and 'Values' labels to axes? Units are currently ambiguous

2024-08-12 21:55 UTC, bellerbrock commented
For charts it would be pretty difficult to add axis labels, they are not supported natively in MPAndroidChart and the workarounds with custom textviews are pretty messy. In my opinion I don't think it's worth it, only case I can think of where the axis meanings wouldn't be apparent from the existing labels (a trait with numbered categories and  little data collected)

2024-11-22 12:09 UTC, trife requested changes
- [ ] Tutorial choice from appintro not being respected when app is loaded
- [ ] Default collect toolbar icons are currently hidden on install until appearance settings are opened (there was some code in configactivity to fix this at one point)
- [ ] Entries are skipped by default when data has been collected until behavior settings are opened

2024-12-01 23:27 UTC, trife approved these changes

2024-12-01 23:27 UTC, merged